package common;

public enum HandlerName {
    VODAFONE_RECHARGE,
    WE_RECHARGE,
    ORANGE_RECHARGE,
    VODAFONE_INTERNET,
    ETISALAT_RECHARGE,
    WE_INTERNET,
    ETISALAT_INTERNET,
    ORANGE_INTERNET,
    QUARTERLY_LANDLINE,
    MONTHLY_LANDLINE,
    NGO_DONATION,
    CANCER_HOSPITAL_DONATION,
    SCHOOL_DONATION
}
