package payments.entities.enums;

public enum ProviderSocketName {
    VODAFONE_RECHARGE_SERVICE,
    ETISALAT_RECHARGE_SERVICE,
    ORANGE_RECHARGE_SERVICE,
    WE_RECHARGE_SERVICE,
    VODAFONE_INTERNET_PAYMENT_SERVICE,
    ETISALAT_INTERNET_PAYMENT_SERVICE,
    ORANGE_INTERNET_PAYMENT_SERVICE,
    WE_INTERNET_PAYMENT_SERVICE,
    MONTHLY_RECEIPT_LANDLINE_SERVICE,
    QUARTERLY_RECEIPT_LANDLINE_SERVICE,
    CANCER_HOSPITAL_DONATION,
    SCHOOL_DONATION,
    NGO_DONATION
}
